// Complete list of all 36 districts of Punjab, Pakistan
export const PUNJAB_DISTRICTS = [
  'Attock',
  'Bahawalnagar',
  'Bahawalpur',
  'Bhakkar',
  'Chakwal',
  'Chiniot',
  'Dera Ghazi Khan',
  'Faisalabad',
  'Gujranwala',
  'Gujrat',
  'Hafizabad',
  'Jhang',
  'Jhelum',
  'Kasur',
  'Khanewal',
  'Khushab',
  'Lahore',
  'Layyah',
  'Lodhran',
  'Mandi Bahauddin',
  'Mianwali',
  'Multan',
  'Muzaffargarh',
  'Nankana Sahib',
  'Narowal',
  'Okara',
  'Pakpattan',
  'Rahim Yar Khan',
  'Rajanpur',
  'Rawalpindi',
  'Sahiwal',
  'Sargodha',
  'Sheikhupura',
  'Sialkot',
  'Toba Tek Singh',
  'Vehari',
];
